### ISSUE TITLE
Demo site's cert is invalid

### ISSUE THREAD

**Issue by jlnunez89** [lucabriguglia/Atles#10]
## Problem
The site hosted at atles.io is serving an invalid cert:
![image](https://user-images.githubusercontent.com/20101933/93728861-c4853b80-fb76-11ea-8cf8-c401d829c15d.png)

Maybe the DNS registration from the name change hasn't propagated correctly.

**Comment by jlnunez89** [comment]
Seems it indeed was DNS propagation, can't repro anymore :)

**Comment by lucabriguglia** [comment]
I know, I have already contacted the registrar. It's an intermittent issue that needs to be resolved.
